# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Giratina.net
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "" # the subpath of the site
url: "https://giratina.net" # the base hostname & protocol for the site
og_image: /assets/img/highgiratina.gif
google_analytics: ""

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: notifications@mail.giratina.net
      link: mailto:notifications@mail.giratina.net
  follow:
    - name: Twitter
      link: https://twitter.com/giratina4545
      username: "@giratina4545"
    - name: GitHub
      link: https://github.com/Giratina-net
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
